//! P1 (IS-1/5): the closure carries its shape, and a hexagon no
//! longer masquerades as a five-simplex.
//!
//! The vectors were generated by an INDEPENDENT implementation
//! (python, from the documents) and are decoded here by the engine's
//! own codec — a cross-implementation pin in both directions.

#![allow(clippy::panic, clippy::unwrap_used, clippy::expect_used)]
#![allow(clippy::indexing_slicing)] // a test that misindexes must fail loudly

use assay::complex::{DeclaredComplex, DEFAULT_FUEL};

fn vector(name: &str) -> Vec<u8> {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    std::fs::read(root.join("../../conformance").join(name)).expect("vector on disk")
}

/// Parse one IS-1/5 shaped-closure frame: tag 51, one shaped grain.
/// Returns (orbs, definition bytes).
fn parse_shaped(frame: &[u8]) -> (Vec<u32>, Vec<u8>) {
    assert_eq!(frame.first(), Some(&51), "tag 51");
    let len = u32::from_le_bytes(frame[1..5].try_into().expect("len")) as usize;
    let value = &frame[5..5 + len];
    assert_eq!(frame.len(), 5 + len, "no trailing bytes");
    let count = u32::from_le_bytes(value[0..4].try_into().expect("count"));
    assert_eq!(count, 1);
    let mut at = 4usize;
    let arity = u32::from_le_bytes(value[at..at + 4].try_into().expect("arity")) as usize;
    at += 4;
    let mut orbs = Vec::new();
    for _ in 0..arity {
        orbs.push(u32::from_le_bytes(value[at..at + 4].try_into().expect("orb")));
        at += 4;
    }
    let dl = u32::from_le_bytes(value[at..at + 4].try_into().expect("def len")) as usize;
    at += 4;
    let definition = value[at..at + dl].to_vec();
    assert_eq!(at + dl, value.len(), "grain is whole");
    (orbs, definition)
}

#[test]
fn the_hexagon_and_the_five_simplex_are_distinct_on_the_wire() {
    let hexagon = vector("17-shaped-closure-hexagon.bin");
    let simplex = vector("18-shaped-closure-simplex.bin");
    assert_ne!(hexagon, simplex, "the defect class, closed at the byte level");

    let (orbs_h, def_h) = parse_shaped(&hexagon);
    let (orbs_s, def_s) = parse_shaped(&simplex);
    assert_eq!(orbs_h, orbs_s, "SAME six orbs — the old frame collapsed here");

    // The engine's own codec reads the independent implementation's
    // bytes, and the declarations are real complexes.
    let hex = DeclaredComplex::decode(&def_h).expect("python bytes, rust reader");
    let simp = DeclaredComplex::decode(&def_s).expect("python bytes, rust reader");
    hex.admit(DEFAULT_FUEL).expect("the hexagon is a complex");
    simp.admit(DEFAULT_FUEL).expect("the simplex skeleton is a complex");
    assert_ne!(hex, simp);
    assert_eq!(hex.cells, vec![6, 6], "six orbs, six edges: the ring");
    assert_eq!(simp.cells, vec![6, 15], "six orbs, fifteen edges: K6");

    // The vertex map law: dimension-0 cell count equals the arity.
    assert_eq!(hex.cells.first().copied(), Some(orbs_h.len() as u32));
    assert_eq!(simp.cells.first().copied(), Some(orbs_s.len() as u32));
}

#[test]
fn the_legacy_grain_is_shape_unknown_not_a_simplex() {
    let legacy = vector("19-shaped-closure-legacy.bin");
    let (orbs, definition) = parse_shaped(&legacy);
    assert_eq!(orbs, (0..6).collect::<Vec<u32>>());
    assert!(
        definition.is_empty(),
        "IS-1/5's legacy form: the shape is EXPLICITLY unknown — a \
         reader must not infer the simplex, or any shape at all"
    );
}
